project:
  type: website
  output-dir: "."

website:
  title: "Daniel Noone" 
  navbar:
    pinned: true
    left:
      - text: 'Class Projects'
        href: class_projects.qmd
      - text: 'Personal Projects'
        href: blog-listing.qmd
      - text: 'Class Blog Posts'
        href: class_blog.qmd
      - text: "Python Data Analysis"
        menu: 
          - basic-python-intro.ipynb
          - danl210-python_only.qmd
          - danl210-reticulate.qmd
  page-footer: 
    center: "Powered with GitHub, Quarto and Rstudio<br>© Daniel Noone, 2023"

format:
  html:
    theme: 
      light: lux
      dark: cyborg
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
